# Generated by Django 5.0.1 on 2026-06-22 13:32

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[applications.validators.SecureFileValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx'], max_size_mb=5)]),
        ),
    ]
