# Generated by Django 5.0.1 on 2026-06-22 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applications_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured'], name='jobs_job_is_feat_3f31c0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-views_count'], name='jobs_job_views_c_b8de09_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at', 'is_active'], name='jobs_job_created_dabd7a_idx'),
        ),
    ]
